/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package at.ssdeck.business.rest.Api;

import at.ssdeck.business.dto.LogInRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-04-07T16:55:22.806765Z[Etc/UTC]")
@Validated
@Tag(name = "User", description = "the User API")
public interface LogInApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /logIn : Log in into exisiting account
     *
     * @param logInRequest  (required)
     * @return Logged in successfully (status code 201)
     *         or Sorry, you have entered invalid Credentails. Try again with your correct login information. (status code 401)
     */
    @Operation(
        operationId = "logIn",
        summary = "Log in into exisiting account",
        tags = { "User" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Logged in successfully"),
            @ApiResponse(responseCode = "401", description = "Sorry, you have entered invalid Credentails. Try again with your correct login information.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/logIn",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> logIn(
        @Parameter(name = "LogInRequest", description = "", required = true) @Valid @RequestBody LogInRequest logInRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
