openapi: 3.0.0
info:
  title: Simple Study Deck Service
  contact:
    name: SSDeck
    url: http://localhost:8080
  version: 1.22.1
servers:
  - url: http://localhost:8080
paths:
  /deck/{card_id}:
    put:
      tags:
          - Card
      summary: Update card
      operationId: updateCard
      parameters:
        - name: card_id
          in: path
          required: true
          description: Id of the card
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Card'
      responses:
        '200':
          description: Updated Card successfully
        '404':
          description: Sorry, this card could not be updated.
    get:
     tags:
        - Card
     summary: Get card by id
     operationId: getCard
     parameters:
        - name: card_id
          in: path
          required: true
          description: Id of the card
          schema:
            type: string
     responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '404':
          description: Sorry, this card could not be found.
    delete:
     tags:
      - Card
     summary: Delete card by id
     operationId: deleteCard
     parameters:
        - name: card_id
          in: path
          required: true
          description: Id of the card
          schema:
            type: string
     responses:
        '200':
          description: Successfully deleted card
        '404':
          description: Sorry, this card could not be deleted .
          
components:
  schemas:
    Card:
      type: object
      properties:
        question:
          type: string
          description: Question of the Card
        answer:
          type: string
          description: Answer of the Question
        card_id:
          type: integer
          description: Id of the card
      required:
        - question
        - answer

    Deck:
      type: array
      items:
        $ref: '#/components/schemas/Card'
